spring:
  application:
    name: BootIOCProj11-LayeredApp-MiniProject
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: tiger
    type: oracle.ucp.jdbc.PoolDataSourceImpl
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
